name: Deploy

on:
  push:
    branches:
      - main

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Test Dependencies
        run: |
          pip install pytest

      - name: Run Tests
        run: |
          pytest test/

  deploy:
    needs: test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        uses: databricks/setup-cli@main

      - name: Validate Bundle
        run: |
          databricks bundle validate

      - name: Deploy Bundle
        run: |
          databricks bundle deploy